#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "no commands are defined. Please refer to the list of available actions."
    exit 1
fi

#  Directory inside Dockerfile should correspond to /p2m2tools_repo directory 
JAR=$(find /p2m2tools_repo/assembly -name "*.jar")

java -cp $JAR $*

