#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "no commands are defined. Please refer to the list of available actions."
    exit 1
fi


JAR=$(find $PWD/assembly -name "p2m2tools*.jar")

java -cp $JAR $*

